export const environment = {
    api:{
        auth:{
            base:'https://localhost:7006',
            rutas:{
                usuario:{
                    login:'/api/Login/login',
                    maquina:'/api/Login/maquina/login',
                    guid:'/api/Login/guid'
                },
                permisos:{
                    grupos:{
                        usuario:'/api/Permisos/usuario/grupos'
                    },
                    aplicaciones:{
                        usuario:'/api/Permisos/usuario/aplicaciones'
                    },elementos:{
                        usuario:'/api/Permisos/usuario/elementos',
                        puede:{
                            actuar:'/api/Permisos/usuario/actua/elemento/{idElemento}'
                        }
                    }
                },
                propiedades:{
                    tipos:'/api/Propiedad/tipos',
                    lista:'/api/Propiedad/lista',
                    elemento:{
                        porIdElemento:'/api/Propiedad/elemento/:idElemento',
                        consulta:'/api/Propiedad/consulta/masiva/elementos',
                        actualiza_anyade:'/api/Propiedad/elemento'
                    }
                },
                administracion:{
                    credenciales:{
                        tipos:{
                            lista:'/api/administracion/usuarios/credenciales/tipos'
                        },
                        lista:{
                            usuario:'/api/administracion/usuarios/usuario/{id}/lista/credenciales'
                        }
                    },
                    aplicaciones:{
                        lista:'/api/administracion/aplicaciones/lista',
                        aplicacion:'/api/administracion/aplicaciones/{id}'
                    },
                    grupos:{
                        lista:'/api/administracion/usuarios/grupos',
                        usuario:'/api/administracion/usuarios/usuario/{id}/lista/grupos'
                    },
                    usuarios:{
                        lista:'/api/administracion/usuarios/lista/{pagina}/{elementos}'
                    }
                }
            }
        }
    }
};