export const environment = {
    api:{
        auth:{
            base:'https://localhost:7006',
            rutas:{
                core:{
                    elementos:{
                        tipos:{
                            lista:'/api/core/elementos/tipos'
                        },
                        estados:{
                            lista:'/api/Core/elementos/estados'
                        }
                    }
                },
                usuario:{
                    login:'/api/Login/login',
                    maquina:'/api/Login/maquina/login',
                    guid:'/api/Login/guid',
                    usuario:'/api/Login/usuario',
                    actualiza:'/api/Login/usuario'
                },
                permisos:{
                    grupos:{
                        usuario:'/api/Permisos/usuario/grupos'
                    },
                    aplicaciones:{
                        usuario:'/api/Permisos/usuario/aplicaciones'
                    },
                    elementos:{
                        usuario:'/api/Permisos/usuario/elementos',
                        puede:{
                            actuar:'/api/Permisos/usuario/actua/elemento/{idElemento}'
                        }
                    }
                },
                propiedades:{
                    tipos:'/api/Propiedad/tipos',
                    lista:'/api/Propiedad/lista',
                    elemento:{
                        porIdElemento:'/api/Propiedad/elemento/:idElemento',
                        consulta:'/api/Propiedad/consulta/masiva/elementos',
                        actualiza_anyade:'/api/Propiedad/elemento'
                    },
                    valores:{
                        permitidos:{
                            propiedad:'/api/Propiedad/valores/permitidos/:codPropiedad',
                            elemento:'/api/Propiedad/valores/permitidos/:codPropiedad/elemento/:idElemento'
                        }
                    }
                },
                administracion:{
                    credenciales:{
                        tipos:{
                            lista:'/api/administracion/usuarios/credenciales/tipos'
                        },
                        lista:{
                            usuario:'/api/administracion/usuarios/usuario/{id}/lista/credenciales'
                        },
                        revocar:'/api/administracion/usuarios/usuario/{id}/credencial/tipo/{codigo}/revocar'
                    },
                    aplicaciones:{
                        lista:'/api/administracion/aplicaciones/lista',
                        aplicacion:'/api/administracion/aplicaciones/{id}',
                        alta:'/api/administracion/aplicaciones',
                        modifica:'/api/administracion/aplicaciones',
                        elementos:{
                            lista:'/api/administracion/aplicaciones/elementos/{id}',
                            tipos:'/api/administracion/aplicaciones/elementos/tipos',
                            alta:'/api/administracion/aplicaciones/elementos/alta',
                            actualizar:'/api/administracion/aplicaciones/elementos/alta',
                            permisos:'/api/administracion/aplicaciones/elementos/permiso/{idAplicacion}/{idGrupo}',
                            tipoPermisos:'/api/administracion/aplicaciones/elementos/tipo/{codigoTipo}/permisos',
                            alta_permiso:'/api/administracion/aplicaciones/elementos/permiso/alta'
                        }
                    },
                    grupos:{
                        lista:'/api/administracion/permisos/grupos',
                        grupo:{
                            ficha:'/api/administracion/permisos/grupos/{id}',
                            usuarios:'/api/administracion/permisos/grupos/{id}/usuarios',
                        },
                        alta:'/api/administracion/permisos/grupos/grupo',
                        actualizacion:'/api/administracion/permisos/grupos/grupo'
                    },
                    usuarios:{
                        lista:'/api/administracion/usuarios/lista/{pagina}/{elementos}',
                        usuario:'/api/administracion/usuarios/{id}',
                        alta:'/api/administracion/usuarios/usuario',
                        actualiza:'/api/administracion/usuarios/usuario',
                        grupos:{
                            lista:'/api/administracion/usuarios/usuario/{id}/lista/grupos',
                            agregar:'/api/administracion/usuarios/usuario/{id}/grupos/agregar',
                            quitar:'/api/administracion/usuarios/usuario/{id}/grupos/quitar'
                        }
                    }
                },
                modulos:{
                    circuitos:{
                        administracion:{
                            tramites:{
                                lista:'/api/modulos/circuitos/administracion/tramites',
                                elemento:'/api/modulos/circuitos/administracion/tramite/:id',
                                alta:'/api/modulos/circuitos/administracion/tramite',
                                modifica:'/api/modulos/circuitos/administracion/tramite'
                            },
                            circuitos:{
                                lista:'/api/modulos/circuitos/administracion/circuitos/listado',
                                elemento:'/api/modulos/circuitos/administracion/circuito/:id',
                                nuevo:'/api/modulos/circuitos/administracion/circuitos/alta',
                                modificar:'/api/modulos/circuitos/administracion/circuitos/modificacion'
                            },
                            Pasos:{
                                lista:'/api/modulos/circuitos/administracion/circuitos/:id/pasos',
                                elemento:'/api/modulos/circuitos/administracion/circuitos/paso/:id',
                                alta:'/api/modulos/circuitos/administracion/circuitos/paso/alta',
                                modificacion:'/api/modulos/circuitos/administracion/circuitos/paso/modificacion',
                                eliminar:'/api/modulos/circuitos/administracion/circuitos/paso/:id',
                                Relacion:{
                                    relaciona:'/api/modulos/circuitos/administracion/circuitos/paso/siguientes/alta',
                                    desrelaciona:'/api/modulos/circuitos/administracion/circuitos/paso/siguientes/elimina'
                                },
                                Acciones:{
                                    lista:'/api/modulos/circuitos/administracion/circuitos/paso/:pasoId/acciones/:tipo'
                                }
                            },
                            Acciones:{
                                lista:'/api/modulos/circuitos/administracion/acciones/listado'
                            },
                            Bandejas:{
                                lista:'/api/modulos/circuitos/administracion/bandejas'
                            }
                        }
                    }
                }
            }
        }
    },
    config:{
        formats:{
            date:{
                    dateShortFormat:'dd-MM-yyyy',
                    dateFormat:'dd-MM-yyyy',
                    dateTime:'dd-MM-yyyy HH:mm'
            }
        }
        
    }
};